apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pxc-deployment
spec:
  replicas: 5 # tells deployment to run N pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: pxc
    spec:
      containers:
      - name: percona-server
        image: perconalab/percona-xtradb-cluster:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "1"
        - name: DISCOVERY_SERVICE
          value: "10.20.2.4:2379"
        - name: CLUSTER_NAME
          value: "k8scluster2"
        - name: XTRABACKUP_PASSWORD
          value: "Theistare"
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        emptyDir: {}
