apiVersion: v1
kind: ReplicationController
metadata:
  name: pxc-rc
  labels:
    app: pxc-app
spec:
  replicas: 3 # tells deployment to run N pods matching the template
  selector:
    app: pxc-app
  template: # create pods using pod definition in this template
    metadata:
      name: pxc
      labels:
        app: pxc-app
    spec:
      containers:
      - name: percona-xtradb-cluster
        image: perconalab/percona-xtradb-cluster:5.6test
        ports:
        - containerPort: 3306
        - containerPort: 4567
        - containerPort: 4568
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Theistareyk"
        - name: DISCOVERY_SERVICE
          value: "172.18.0.4:4001"
        - name: CLUSTER_NAME
          value: "k8scluster2"
        - name: XTRABACKUP_PASSWORD
          value: "Theistare"
        imagePullPolicy: Always
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        emptyDir: {}
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: proxysql-rc
  labels:
    app: proxysql-app
spec:
  replicas: 1 # tells deployment to run N pods matching the template
  selector:
    front: proxysql
  template: # create pods using pod definition in this template
    metadata:
      name: proxysql
      labels:
        app: pxc-app
        front: proxysql
    spec:
      containers:
      - name: proxysql
        image: perconalab/proxysql
        ports:
        - containerPort: 3306
        - containerPort: 6032
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Theistareyk"
        - name: DISCOVERY_SERVICE
          value: "172.18.0.4:4001"
        - name: CLUSTER_NAME
          value: "k8scluster2"
        - name: MYSQL_PROXY_USER
          value: "proxyuser"
        - name: MYSQL_PROXY_PASSWORD
          value: "s3cret"
---
apiVersion: v1
kind: Service
metadata:
  name: pxc-service
  labels:
    app: pxc-app
spec:
  ports:
    # the port that this service should serve on
    - port: 3306
      targetPort: 3306
      name: "mysql"
    - port: 6032
      targetPort: 6032
      name: "proxyadm"
  # label keys and values that must match in order to receive traffic for this service
  selector:
    front: proxysql
