version: '2'

services:
  pmm_data:
    image: percona/pmm
    container_name: pmm_data
    volumes:
      - /var/lib/mysql
      - /opt/prometheus/data
      - /opt/prometheus/targets
    entrypoint: /bin/true

  pmm:
    build: .
    container_name: pmm 
    image: percona/pmm
    environment:
      - ADDRESS=192.168.56.107
    ports:
      - "9001-9003:9001-9003"
      - "3000:3000"
      - "9090:9090"
      - "80:80"
    volumes_from:
      - pmm_data
