global:
  scrape_interval:     1s
  scrape_timeout:      1s
  evaluation_interval: 5s
 
scrape_configs:
  - job_name: prometheus
    target_groups:
      - targets: ['localhost:9090']

  - job_name: linux
    file_sd_configs:
    - names: ['/opt/prometheus/targets/9100.yml']

  - job_name: mysql-hr
    file_sd_configs:
    - names: ['/opt/prometheus/targets/9104.yml']

  - job_name: mysql-mr
    scrape_interval:    5s
    scrape_timeout:     1s
    file_sd_configs:
    - names: ['/opt/prometheus/targets/9105.yml']

  - job_name: mysql-lr
    scrape_interval:   60s
    scrape_timeout:     5s
    file_sd_configs:
    - names: ['/opt/prometheus/targets/9106.yml']

